---
name: dummy

on:
  push:
    branches:
      - trying
      - staging
      - master
  pull_request:
    branches:
      - '*'
jobs:
  dummy-test:
    name: Dummy-test Just To verify
    runs-on: ubuntu-latest

    steps:
      - name: Nothing
        run: echo "Hello World"
